<?php

namespace App\Filament\Resources\CibilResource\Pages;

use App\Filament\Resources\CibilResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateCibil extends CreateRecord
{
    protected static string $resource = CibilResource::class;
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
