<?php

namespace App\Filament\Resources\CibilResource\Pages;

use App\Filament\Resources\CibilResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditCibil extends EditRecord
{
    protected static string $resource = CibilResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
