<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use App\Notifications\CreatePasswordNotification;
use App\Notifications\ResetPasswordNotification;
use Filament\Actions;
use App\Mail\CreatePasswordMail;
use Filament\Facades\Filament;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    protected function afterCreate(): void
    {
        $token = Str::random(60);

        DB::table('password_reset_tokens')->insert([
            'email' => $this->record->email,
            'token' => Hash::make($token),
            'created_at' => now(),
        ]);

        $notification = new ResetPasswordNotification($token);
        $notification->url = Filament::getResetPasswordUrl($token, $this->record);
        $this->record->notify($notification);
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
